CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY,
  number INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  deadline DATETIME NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
